Repository The-Strategy-Unit/nhp_inputs, pull requests merged in 2025-05, with the labels that each got.

#484 Upgrade to insert inequalities
  app.R
  default_params.json
  deploy.R
Labels: enhancement, must

#485 fixes bug in model run submission
  DESCRIPTION
  R/mod_run_model_api_calls.R
  R/mod_run_model_server.R
  manifest.json
Labels: bug, must

#487 bumps to v3.5.0
  DESCRIPTION
Labels: documentation, must
