Repository The-Strategy-Unit/nhp_inputs, pull requests merged in 2025-07, with the labels that each got.

#528 Update manifest
  manifest.json
Labels: enhancement, must

#532 Make README clarifications, add 'test in dev' section
  README.Rmd
  README.md
Labels: documentation, should

#530 Provide text instead of top-6 OP diagnoses table
  R/app_ui.R
  R/mod_mitigators_ui.R
Labels: techdebt, should
