Repository The-Strategy-Unit/nhp_inputs, pull requests merged in 2025-03, with the labels that each got.

#418 removing text referring to uploading previous parameters
  home.md
Labels: documentation, must

#413 Correct underscore to hyphen in `value-type`
  R/app_server.R
  R/mod_mitigators_server.R
  inst/app/data/ndg_variants.json
Labels: bug, must

#424 Upgrade scenarios to NDG3, prevent upgrade of NDG1 scenarios
  app.R
  config.yml
  deploy.R
Labels: enhancement, must

#421 Show NDG dropdown to all users, add variant to table title
  R/mod_non_demographic_adjustment_server.R
  R/mod_non_demographic_adjustment_ui.R
  R/mod_non_demographic_adjustment_utils.R
Labels: enhancement, should

#429 Reinstate 'include' checkbox observer for mitigators
  R/mod_mitigators_server.R
Labels: bug, must

#432 uses correct variable in prod deploy action
  .github/workflows/connect-publish-prod.yaml
Labels: bug, actions, must

#438 Prefer to show the end year from params as the 'model financial year'
  app.R
Labels: bug, must

#439 Isolate NDG variant from params
  R/mod_non_demographic_adjustment_server.R
Labels: bug, must

#440 Ensure 'start' is shown when creating new from scratch
  app.R
Labels: bug, must

#441 425 update text of frailty mitigators to refer to 75
  inst/app/strategy_text/emergency_elderly.md
  inst/app/strategy_text/frail_elderly.md
Labels: documentation, must
