Repository The-Strategy-Unit/nhp_inputs, pull requests merged in 2025-04, with the labels that each got.

#454 adds ability to deploy to new connect server
  deploy.R
Labels: enhancement, should

#459 Upgrade for v3.4 by removing AEC mitigators from params
  app.R
  deploy.R
Labels: enhancement, must

#457 Add SDEC and remove AEC mitigators
  R/app_server.R
  R/app_ui.R
  R/mod_mitigators_summary_server.R
  inst/app/data/mitigator-codes.Rds
  inst/app/data/mitigator-codes.csv
  inst/app/strategy_text/same_day_emergency_care.md
  inst/golem-config.yml
Labels: enhancement, must

#461 remove file from demographic_factors in default params
  default_params.json
Labels: enhancement, should

#463 Tweak SDEC strategy text
  inst/app/strategy_text/same_day_emergency_care.md
Labels: documentation, enhancement, must

#458 adds ability to change the list of population projections displayed to a user
  R/app_ui.R
  R/fct_population_growth.R
  R/mod_population_growth_server.R
  R/mod_population_growth_ui.R
  inst/golem-config.yml
Labels: enhancement

#464 change number format of sdec mitigators
  inst/golem-config.yml
Labels: bug, must

#466 removes the file key from demographic factors when upgrading
  app.R
  deploy.R
Labels: enhancement, could

#467 updates lintr defaults
  .lintr
Labels: enhancement, could

#468 fixes golem config, missing "
  inst/golem-config.yml
Labels: bug, must

#470 Correct typo when removing 'file' key from params
  app.R
Labels: bug

#469 format with air
  .Rbuildignore
  .Rprofile
  .github/workflows/R-CMD-check.yaml
  .github/workflows/check.yaml
  .renvignore
  DESCRIPTION
  R/ZZZ.R
  R/app_config.R
  R/app_server.R
  R/app_ui.R
  R/fct_age_pyramid.R
  R/fct_azure_storage.R
  R/golem_utils_server.R
  R/golem_utils_ui.R
  R/mod_baseline_adjustment_server.R
  R/mod_baseline_adjustment_ui.R
  R/mod_covid_adjustment_server.R
  R/mod_expat_repat_server.R
  R/mod_expat_repat_ui.R
  R/mod_expat_repat_utils.R
  R/mod_inequalities_server.R
  R/mod_mitigators_funnel_plot.R
  R/mod_mitigators_rates_boxplot.R
  R/mod_mitigators_rates_trend_plot.R
  R/mod_mitigators_server.R
  R/mod_mitigators_summary_server.R
  R/mod_mitigators_summary_ui.R
  R/mod_mitigators_ui.R
  R/mod_non_demographic_adjustment_server.R
  R/mod_non_demographic_adjustment_ui.R
  R/mod_non_demographic_adjustment_utils.R
  R/mod_reasons_server.R
  R/mod_run_model_api_calls.R
  R/mod_run_model_fix_params.R
  R/mod_run_model_server.R
  R/mod_time_profile_server.R
  R/mod_waiting_list_imbalances_server.R
  R/run_app.R
  README.Rmd
  README.md
  app.R
  man/load_provider_data.Rd
  renv.lock
  renv/.gitignore
  renv/activate.R
  renv/settings.json
Labels: enhancement, actions, could

#473 Recorrect names of frailty mitigators
  inst/app/data/mitigator-codes.csv
Labels: enhancement, must
