Repository The-Strategy-Unit/nhp_inputs, pull requests merged in 2025-06, with the labels that each got.

#496 fix caching
  R/app_server.R
  R/mod_baseline_adjustment_server.R
  R/mod_covid_adjustment_server.R
  R/mod_expat_repat_server.R
  R/mod_waiting_list_imbalances_server.R
Labels: bug, must

#498 adds custom variants
  inst/golem-config.yml
Labels: enhancement, must

#504 Remove waiting list imbalances from UI
  R/app_ui.R
  R/golem_utils_ui.R
  R/mod_mitigators_server.R
Labels: enhancement, must

#506 Bump to v3.6.0
  DESCRIPTION
Labels: documentation, must

#509 fix end year bug
  app.R
Labels: bug
